---
model:
  hidden_dim: 256
  num_layers: 1
  vocab_size: 114
  model: ssm # rnn, ssm, transformer

  # SSM only
  d_model: 256
  d_output: 113 # number of possible predicted values
  n: 64 
  l_max: 3 
  collapse: true
  
data:
  modulo: 113
  train_frac: 0.3
  data_seed: 42
  seq_length: 3 # ssm only
  operation: addition

training:
  epochs: 10000
  lr: 0.001
  wd: 1e-05
  betas: [0.9, 0.99]
  use_scheduler: false
  lr_decay_interval: 5000
  lr_decay: 0.1
  save_every: 2000

  # Regularization
  fourier_regularization: 0
  regularization_parameter: 1e-4
  activity: 0