operations:
  - addition
model_type: transformer

data:
  modulo: 31
  nterms: 2
  train_frac: 0.3
  data_seed: 598
  vocab_size: 0

analysis:
  fourier_norm_threshold: 0.1
  freq_threshold_top_fraction: 0.1
  freq_threshold_min_components: 4
  freq_threshold_fixed: 0.1

model:
  model_type: transformer
  vocab_size: 0
  embedding_dim: 256
  n_heads: 1
  n_layers: 1
  dim_feedforward: 256
  dropout: 0.1
  max_len: 128
  fixed_positional_encoding: false
  activation: relu
  norm_first: false
  mask: true
  tie_weights: false

training:
  epochs: 100
  lr: 0.001
  wd: 5.0e-05
  beta1: 0.9
  beta2: 0.99
  use_scheduler: true
  lr_decay_interval: 5000
  lr_decay: 0.1
  save_every: 100
  save_dir: transformer_modular_addition_sample
  batch_mode: full
  batch_size: 512
  training_target: last_token
  cot_prefix_weight: 1.0
  cot_final_weight: 1.0
  fourier_reg_mode: null
  fourier_reg_coefficient: 0.0
  fourier_reg_groups: 2
  dataloader_num_workers: 0
  betas:
    - 0.9
    - 0.99
