operations:
- addition
- division
model_type: transformer
data:
  modulo: 113
  train_frac: 0.35
  data_seed: 598
  includes_zero: true
  vocab_size: 116
model:
  model_type: transformer
  vocab_size: 116
  embedding_dim: 512
  n_heads: 8
  n_layers: 1
  dim_feedforward: 1024
  dropout: 0.1
  max_len: 128
  fixed_positional_encoding: false
  activation: relu
  norm_first: false
  mask: false
  tie_weights: false
training:
  epochs: 10000
  lr: 0.001
  wd: 1.0
  beta1: 0.9
  beta2: 0.99
  use_scheduler: true
  lr_decay_interval: 5000
  lr_decay: 0.1
  save_every: 1000
  save_dir: transformer_modular_addition_division
  batch_mode: operation-batch
  batch_size: 512
  fourier_reg_mode: 7
  fourier_reg_coefficient: 0.0001
  betas:
  - 0.9
  - 0.99
