operations:
- addition
- multiplication
model_type: transformer
data:
  modulo: 113
  train_frac: 0.35
  data_seed: 123
  vocab_size: 116
model:
  model_type: transformer
  vocab_size: 116
  embedding_dim: 512
  n_heads: 8
  n_layers: 1
  dim_feedforward: 1024
  dropout: 0.0
  max_len: 4
  fixed_positional_encoding: false
  activation: relu
  norm_first: false
  mask: false
  tie_weights: false
training:
  epochs: 10000
  lr: 0.001
  wd: 1.0
  beta1: 0.9
  beta2: 0.99
  use_scheduler: true
  lr_decay_interval: 5000
  lr_decay: 0.1
  save_every: 1000
  save_dir: experiments/transformer_op_pairs/914376_f864bb220d/transformer_modular_addition_multiplication
  batch_mode: operation-batch
  batch_size: 512
  fourier_reg_mode: 1
  fourier_reg_groups: 4
  fourier_reg_coefficient: 0.00002
  betas:
  - 0.9
  - 0.99